# Generated by Django 4.2.1 on 2023-06-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_date_of_death'),
    ]

    operations = [
    ]
